### ISSUE TITLE
Will the source code of this work be available on GitHub?

### ISSUE THREAD

**Issue by DerSchatten01** [siyandong/NeuralCoMapping#1]
Hi，I am a senior student in WHU and I am interesting in multi-robot SLAM. I have read your paper in CVPR 2022，it is really impressive, however, I can not understand some parts of your work. So, may I venture to ask that will the source code of NeuralCoMapping be avaiable on GitHub so I can compile it and do some test to improve my understanding of your work.

Best regards.

**Comment by siyandong** [comment]
The code will be released soon.
