### ISSUE TITLE
关于action没有定义问题

### ISSUE THREAD

**Issue by knowthyself9** [siyandong/NeuralCoMapping#14]
如下图在ma_env_base.py文件，第762和764行的action变量是之前没有定义吗？目前vscode提示没有定义

![2024-01-09 21-41-08 的屏幕截图](https://github.com/siyandong/NeuralCoMapping/assets/48142254/a467b553-970a-4aae-8d40-48b91033f4bd)

**Comment by illusive-chase** [comment]
这是一段iGibson的原始代码，在我们的项目中永远不会触发；原始代码针对单机器人设置，因此我们将其改为多机器人时，将action改为了actions，但是这一段中未作修改，所以显示未定义，你可以直接删除 L760-L765 。

**Comment by knowthyself9** [comment]
明白了，谢谢
