### ISSUE TITLE
关于cuda问题

### ISSUE THREAD

**Issue by knowthyself9** [siyandong/NeuralCoMapping#16]
![2024-01-11 18-41-59 的屏幕截图](https://github.com/siyandong/NeuralCoMapping/assets/48142254/438dcdac-3293-4416-8bb9-91cca4549b9c)
如上图，我运行这行指令，出现cuda问题，不太明白这个问题，如何解决。上面那个黄色警报要求python3.7版本，而我的虚拟环境按要求装的是3.6版本，是否需要升级为3.7版本，这个是否必要。

**Comment by fish-x-y** [comment]
您好，请问最后问题如何解决的。
