### ISSUE TITLE
Can you please provide me with the environmental information?

### ISSUE THREAD

**Issue by JaycgbEDC** [siyandong/NeuralCoMapping#17]
Now I'm running your code on the server (following the steps you provided), and I encountered an error: "ERROR: Failed to EGL with glad." Additionally, when running it on a Mac, it gets stuck at the line `main.construct_envs(args, snp.dump())` and does not progress.

**Comment by illusive-chase** [comment]
I think it may be related to the iGibson emulator we use (which seems to rely on some kind of OpenGL environment). For example, this URL [https://github.com/StanfordVL/iGibson/issues/354](https://github.com/StanfordVL/iGibson/issues/354) points to a similar issue, but it is not answered.

(And we have only verified the feasibility of the program on Linux. Therefore, it may not work properly on a Mac.)

**Comment by JaycgbEDC** [comment]
> I think it may be related to the iGibson emulator we use (which seems to rely on some kind of OpenGL environment). For example, this URL [StanfordVL/iGibson#354](https://github.com/StanfordVL/iGibson/issues/354) points to a similar issue, but it is not answered.
> 
> (And we have only verified the feasibility of the program on Linux. Therefore, it may not work properly on a Mac.)

Thank you for your reply！By the way，can you please tell me about the ubuntu's version？（maybe I can try in Mac‘s virtual machine）

**Comment by illusive-chase** [comment]
Sure. It is ubuntu 20.04

**Comment by JaycgbEDC** [comment]
> Sure. It is ubuntu 20.04

ok，thanks
