### ISSUE TITLE
global_input 的9个内容分别都是哪些

### ISSUE THREAD

**Issue by DioBakery** [siyandong/NeuralCoMapping#18]
请问global_input 的9个内容分别都是哪些？和论文中的4个自图和3个交叉图又是怎么对应的？

**Comment by illusive-chase** [comment]
- global_input的相关代码注释 [https://github.com/siyandong/NeuralCoMapping/blob/main/utils/map_manager.py#L60-L61](https://github.com/siyandong/NeuralCoMapping/blob/main/utils/map_manager.py#L60-L61) 中描述了其内容

- “论文中的4个自图和3个交叉图”这里分别是self-attention和cross-attention，详见AttentionalGNN这个类及相关代码 [https://github.com/siyandong/NeuralCoMapping/blob/main/utils/gnn.py#L234](https://github.com/siyandong/NeuralCoMapping/blob/main/utils/gnn.py#L234)
