### ISSUE TITLE
请问论文中论文中图操作中注意力机制的l是什么意义？是指每次图操作都有多层点特征更新吗？还是每进行一次图操作都更新一次特征？

### ISSUE THREAD

**Issue by DioBakery** [siyandong/NeuralCoMapping#19]

**Comment by illusive-chase** [comment]
你是说下标 `i` 吗？指第 `i` 个机器人；
如果说的是上标 `l` (L的小写），指的是图神经网络中第 `l` 层。

**Comment by DioBakery** [comment]
> 你是说下标 `i` 吗？指第 `i` 个机器人； 如果说的是上标 `l` (L的小写），指的是图神经网络中第 `l` 层。

我指的是上标小写L，意思是每一次global act都将进行图操作，然后每次图操作都是通过将特征从v和e经过L层图神经网络更新到v(L)和e(L)是吗

**Comment by illusive-chase** [comment]
是的
