### ISSUE TITLE
关于获取Gibson数据集

### ISSUE THREAD

**Issue by fish-x-y** [siyandong/NeuralCoMapping#20]
![123122320240829161252](https://github.com/user-attachments/assets/195fdeaa-36d8-4175-9b53-dafa879c8d3e)
您好，通过链接找到URL，将python -m gibson2.utils.assets_utils --download_dataset {URL}运行，得到如图结果，不知道哪里出了问题。

**Comment by illusive-chase** [comment]
命令行里不要保留大括号

**Comment by fish-x-y** [comment]
> 命令行里不要保留大括号

![微信图片_20240829212844](https://github.com/user-attachments/assets/e0989d13-73bf-4684-856e-67fea83a10a8)
您好，去掉括号之后，还是有问题。

**Comment by illusive-chase** [comment]
这个网址不是很对吧，我印象应该是storage.googleapis.com开头的，结尾是个tar.gz

**Comment by fish-x-y** [comment]
非常感谢
