### ISSUE TITLE
关于USAGE中的Train部分

### ISSUE THREAD

**Issue by fish-x-y** [siyandong/NeuralCoMapping#21]
您好，我执行Train部分的对应代码，遇到如下问题。请问有什么解决办法吗。
![wechat_2024-09-11_160718_191](https://github.com/user-attachments/assets/5eb21fe7-3906-417d-a92c-66252bde8bf8)

**Comment by illusive-chase** [comment]
用 `--cuda 0` 指定使用的CUDA设备序号

**Comment by fish-x-y** [comment]
您好，指定使用的CUDA设备序号后，出现如下情况。
![wechat_2024-09-12_205019_782](https://github.com/user-attachments/assets/c5b31c78-e22f-4025-a6f9-98a20154bd6a)

**Comment by fish-x-y** [comment]
感谢您的回复，后续在执行Train部分对应代码时，再次遇到如下问题。
![wechat_2024-09-13_213504_633](https://github.com/user-attachments/assets/b3c6b2f5-c250-4558-85af-371c1d65c7d5)
