### ISSUE TITLE
关于Train遇到的问题

### ISSUE THREAD

**Issue by fish-x-y** [siyandong/NeuralCoMapping#22]
您好，执行 python main.py --global_lr 5e-4 --exp_name 'ma3_history' --critic_lr_coef 5e-2 --train_global 1 --dump_location train --scenes_file scenes/train.scenes 之后出现如下情况，请问如何解决。
![截图 2024-09-17 17-46-52](https://github.com/user-attachments/assets/81735639-ceca-40b8-a4cf-b288399649ee)

**Comment by illusive-chase** [comment]
看起来是你使用的环境中opengl的驱动问题，这个我就不太清楚了

**Comment by fish-x-y** [comment]
好的，感谢回复
