### ISSUE TITLE
Frontier comutation and cluster

### ISSUE THREAD

**Issue by vincent341** [siyandong/NeuralCoMapping#4]
Hi. Thanks so much for sharing the code. Would you mind letting me know where the codes for computing frontiers and clustering them are? Appreciate it very much.

**Comment by illusive-chase** [comment]
Thanks for your attention.

Here we compute frontiers:
https://github.com/siyandong/NeuralCoMapping/blob/9edd0cd9db7687752813c50fa88f4dcf44eed42a/env/gibson_api/exploration_env.py#L467

And we downsample them in https://github.com/siyandong/NeuralCoMapping/blob/9edd0cd9db7687752813c50fa88f4dcf44eed42a/utils/map_manager.py.

**Comment by vincent341** [comment]
> Thanks for your attention.
> 
> Here we compute frontiers:
> 
> https://github.com/siyandong/NeuralCoMapping/blob/9edd0cd9db7687752813c50fa88f4dcf44eed42a/env/gibson_api/exploration_env.py#L467
> 
> And we downsample them in https://github.com/siyandong/NeuralCoMapping/blob/9edd0cd9db7687752813c50fa88f4dcf44eed42a/utils/map_manager.py.

Thanks very much for your quick reply.
