### ISSUE TITLE
No module named 'env'

### ISSUE THREAD

**Issue by JiaWenHa** [siyandong/NeuralCoMapping#8]
运行 python main.py --global_lr 5e-4 --exp_name 'ma3_history' --critic_lr_coef 5e-2 --train_global 1 --dump_location train --scenes_file scenes/train.scenes
出现以下问题：
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    from env.gibson_api import construct_envs
ModuleNotFoundError: No module named 'env'

**Comment by illusive-chase** [comment]
That's unusual...
What is your Python version?

**Comment by JiaWenHa** [comment]
> That's unusual... What is your Python version?

Now my running environment is Python 3.6.15， gym-0.12.0
Below is a screenshot of my running：
![图片](https://user-images.githubusercontent.com/108913515/224466552-649de830-17e7-4876-8334-49cda0db118f.png)

**Comment by JiaWenHa** [comment]
> That's unusual... What is your Python version?

Found the reason, because my 'env' folder was missing, thanks
