### ISSUE TITLE
About Sinkhorn output

### ISSUE THREAD

**Issue by JiayunjieJYJ** [siyandong/NeuralCoMapping#9]
Thank you for your excellent work, and I have an issue I'd like to discuss with you.
Sinkhorn's output is the result of several rounds of raw and column normalization, but I wonder what happens if two robots pick the same frontier?  For example, the following Sinkhorn's output ：
![image](https://user-images.githubusercontent.com/44229958/226091090-63a3d099-b04d-4981-9fc8-c2698701d2e7.png)
final matching matrix:
![image](https://user-images.githubusercontent.com/44229958/226091146-21f64dce-89fb-44f4-aa60-211f57286d02.png)

How does your code solve this problem?

Thanks!

**Comment by illusive-chase** [comment]
It would be possible that two robots pick the same frontier (they will just try to move towards the same goal position).
However, a well-trained policy will avoid that to achieve higher efficiency.

**Comment by JiayunjieJYJ** [comment]
> It would be possible that two robots pick the same frontier (they will just try to move towards the same goal position). However, a well-trained policy will avoid that to achieve higher efficiency.

OK, thanks! Now I have more problems [reproducing it.](https://github.com/siyandong/NeuralCoMapping/issues/10) Hope you can help me. Thanks!
